implement reset password functionality
HF-RapidResponse/volunteer-portal pull request #109
Opened 2021-03-29 01:46 UTC by ecaoile

Figured this was simple enough to implement over a weekend.
- modal to request a password reset is on the login page (can enter e-mail or username), changes view on successful submit
- user receives e-mail with URL including a hash param to reset password (expires in 15 minutes from request)
- after entering password, client lets user know reset was success and provides a link back to the login page

2021-03-29 17:32 UTC, jtuckerk requested changes
There are a couple of funky things but overall you're continuing to kill it.

2021-03-29 17:32 UTC, jtuckerk commented on api/account_api.py
> +                existing_acct.username + str(curr_time))
We'll need to include something random in here, or just pick a random number. if someone who doesnt own the account sends a password reset request they know roughly the time and the username theyre trying to hack so just a few checks and they can get the string then use the same encrypt function since this code is public and get the reset hash

2021-03-29 17:32 UTC, jtuckerk commented on api/account_api.py
> +                you cannot set or reset a password.</p>'
Can we add, "please try signing in with  {existing_acct.oauth.capitalize()}"

2021-03-29 17:32 UTC, jtuckerk commented on client/src/components/Login.js
> +                Forgot password?
Can we make "Forgot Password?" stand out a little more as a link? underlined or centered or maybe even make it a little button? not sure whats best, but it's subtle as is
![image](https://user-images.githubusercontent.com/8518434/112872860-dd732a00-908e-11eb-9c0c-1073a57e55b2.png)

2021-03-29 17:32 UTC, jtuckerk commented on client/src/components/modals/ForgotPasswordModal.js
> +                placeholder="Enter username or e-mail address (required)"
I dont think "(required)" is necessary since theres only one box and an error shows if its empty. it also overruns the side of the input box on some devices
![image](https://user-images.githubusercontent.com/8518434/112873131-38a51c80-908f-11eb-8b32-4a6b117e4fff.png)

2021-03-29 17:32 UTC, jtuckerk commented on api/account_api.py
> +    if existing_acct is not None:
When walking through the password reset flow the email didn't send for my username, but did send for my email

2021-03-29 17:32 UTC, jtuckerk commented on api/account_api.py
> +        email_message = f'<p>Dear {existing_acct.first_name},</p>'
When I reset the password I got the green check marks on the new password fields, but no other indication that it was correct, nor a redirect to the login page.

I somehow got in a bad state when I continued on after resetting the password. I tried logging in using my old password first and it still worked, then I logged out and tried the new password and it didnt work. then after a bit I tried logging out and started seeing "DELETE /api/logout HTTP/1.0" 401 Unauthorized" in the api logs. so maybe the password reset took a minute and the the token got revoked? or something?

2021-03-29 19:32 UTC, ecaoile commented on api/account_api.py
> +                existing_acct.username + str(curr_time))
added random numbers

2021-03-29 19:32 UTC, ecaoile commented on api/account_api.py
> +                you cannot set or reset a password.</p>'
added sentence

2021-03-29 19:33 UTC, ecaoile commented on client/src/components/Login.js
> +                Forgot password?
@cynthiatai Any ideas for how this should look?

2021-03-29 19:33 UTC, ecaoile commented on api/account_api.py
> +    if existing_acct is not None:
Oops, I got carried away with copypasta and searched for email twice. Fixed.

2021-03-29 19:33 UTC, ecaoile commented on api/account_api.py
> +        email_message = f'<p>Dear {existing_acct.first_name},</p>'
Hmm, I can't seem to repro this...

2021-03-29 19:39 UTC, ecaoile commented on client/src/components/modals/ForgotPasswordModal.js
> +                placeholder="Enter username or e-mail address (required)"
removed

2021-03-30 05:39 UTC, ecaoile commented on client/src/components/Login.js
> +                Forgot password?
Cynthia said to just underline it. Is this ok?
![image](https://user-images.githubusercontent.com/34725510/112938999-92cdce00-90df-11eb-9770-d7a97f86d410.png)

2021-04-01 17:47 UTC, jtuckerk commented on client/src/components/Login.js
> +                Forgot password?
yes I think that helps a lot!

2021-04-01 18:25 UTC, jtuckerk commented on api/account_api.py
> +        email_message = f'<p>Dear {existing_acct.first_name},</p>'
hmm yeah me neither.

2021-04-01 18:33 UTC, jtuckerk approved these changes
It's looking good!

one last thing: I think there's a validity check mismatch for usernames, I can't tell quite where since the validity checking syntax is confusing to me, but in creating an account it lets me create tuck, but when I go to use that to retrieve my reset it triggers the not >4 char error

2021-04-01 18:37 UTC, jtuckerk commented
ooh also I think this is more of a feature than a bug, but im not sure if it's intential. 
I can create an account using the basic account creation, and then later log in with oauth for that email. it saves things like my original username so that's good. would probably preserve my initiative preferences too. My only worry would be something like the "oauth" field in the account db entry being wrong and later causing issues. maybe for password reset or something. 

also not added in this PR.  just noting it here.

2021-04-01 19:09 UTC, ecaoile commented
> 
> 
> ooh also I think this is more of a feature than a bug, but im not sure if it's intential.
> I can create an account using the basic account creation, and then later log in with oauth for that email. it saves things like my original username so that's good. would probably preserve my initiative preferences too. My only worry would be something like the "oauth" field in the account db entry being wrong and later causing issues. maybe for password reset or something.
> 
> also not added in this PR. just noting it here.

I noticed that too. I think if you oauth login an existing account that was created with basic auth, it leaves the oauth field as null. That means you'll still be allowed to reset password. I don't know if we wanted to disable it...but I think we could maybe add some stuff like adding the oauth profile pic if they don't already have one

2021-04-02 17:33 UTC, merged