Adding account registration confirmation e-mail for basic auth accounts
HF-RapidResponse/volunteer-portal pull request #117
Opened 2021-04-19 01:27 UTC by ecaoile

Requiring users to open an e-mail and confirm registration if they didn't log in with OAuth. This shouldn't affect OAuth users at all.

2021-04-19 16:00 UTC, jtuckerk reviewed
I'm not sure if this is ready to go or not yet, but I tested it!
I like the option to undo the account creation, thats a good feature!

Is it possible/ easy to skip the login step after the verification? like have the verify account link send them a token and land them at the account settings page? having to retype my email and password is a buzzkill

2021-04-19 16:54 UTC, ecaoile commented
> 
> 
> I'm not sure if this is ready to go or not yet, but I tested it!
> I like the option to undo the account creation, thats a good feature!
> 
> Is it possible/ easy to skip the login step after the verification? like have the verify account link send them a token and land them at the account settings page? having to retype my email and password is a buzzkill

I was going to write tests before having someone review it and also wanted to verify the current tests were working on here. Almost done...but yes, I can generate a token and have them log back in. Will probably set a 3 second timer so they have time to read the text.

2021-04-22 05:09 UTC, ecaoile commented on api/tests/test_account_api.py
> +    # settings = resp.json()
@jtuckerk @trippersham need help getting this commented out part to work. It can't seem to read the verify_account_hash and the cancel_registration_hash that I added recently. I don't know how to update the test API to include the new props, and I don't know how to get the tests working locally either.

2021-04-22 16:38 UTC, jtuckerk commented on api/tests/test_account_api.py
> +    # settings = resp.json()
you were just missing the fields in the API schema. It was only a matter of time before that bit someone in the but. I didn't like having essentially duplicate definitions for the db model and the API schema, but we do need that separation so we can have requests/responses with a subset of the db fields. I think for now it's a necessary evil.

 I've pushed a change that adds the fields and fixes the tests

2021-04-22 16:41 UTC, jtuckerk commented on api/tests/test_account_api.py
> +    # settings = resp.json()
On second thought we probably don't need to expose those through the API. I dont think there is any harm in it so I might just leave it.

If you think of some way that could be insecure, we can update the tests to access the DB directly to check that those fields are populated.

2021-04-22 16:55 UTC, ecaoile commented on api/tests/test_account_api.py
> +    # settings = resp.json()
Oh silly me, I updated it for password reset hash but totally forgot it for verify. RIP

I don't think exposing hashes through the API is too big of a deal. I mean there's inherently going to be a potential security issue with allowing people to verify through a URL...but we want them to be able to register through a URL.

2021-04-22 17:27 UTC, jtuckerk requested changes
only 1 thing I think it's worth changing

2021-04-22 17:27 UTC, jtuckerk commented on api/account_api.py
> -    return minutes_diff
Breaking all of this into its own file was the right call :)

2021-04-22 17:27 UTC, jtuckerk commented on api/auth.py
> +            status_code=403, detail=f"E-mail or password is invalid!")
+1

2021-04-22 17:27 UTC, jtuckerk commented on api/notifications_api.py
> +    db.delete(settings_to_delete)
just to be safe, can we call the same method as the API calls to delete the account? we may need to pull the account delete function out into one more level of function calls since I'm not sure how/if we should call the router decorated function directly.
I think for now this is logically correct since it cleans up the account and the settings dbs, but in the future if we do things like remove a volunteer or admin from a group DB we can do that all from the same function and not have to update it here and elsewhere.

2021-04-22 17:27 UTC, jtuckerk commented on api/tests/test_account_api.py
> -    resp = new_client.post(f'api/auth/basic', json={'email':'rebecca03@thomasrivera.com',
what tools are you using to auto format? I'll try to install the same one/similar and maybe include it in the README so we can all be formatting the same way and avoid some noise in these reviews

2021-04-22 17:27 UTC, jtuckerk commented on client/src/store/user-slice/index.js
> +      await axios.post(`/api/notifications/`, obj);
No need to update this now, but my leaning is to run things like this from within the create call in the api just to avoid a possible failure between http calls

2021-04-22 22:05 UTC, ecaoile commented on api/tests/test_account_api.py
> -    resp = new_client.post(f'api/auth/basic', json={'email':'rebecca03@thomasrivera.com',
I have ESLint and Prettier installed in VS Code. That might be redundant, but it is reading off our eslintrc.json file in the client.

2021-04-22 23:44 UTC, ecaoile commented on api/notifications_api.py
> +    db.delete(settings_to_delete)
I thought about that, but the reason I didn't do it was because the client doesn't have a token at that point. I guess we can inject a token creation, but that seems a little weird since the user is going to disappear right away.

2021-04-22 23:49 UTC, ecaoile commented on client/src/store/user-slice/index.js
> +      await axios.post(`/api/notifications/`, obj);
Hmmm, I have mixed feelings on that. The notification is outside the scope of accounts. Something feels dirty about doing that, but yes, we can reduce the number of calls by combining stuff

2021-04-23 05:09 UTC, ecaoile commented on api/notifications_api.py
> +    db.delete(settings_to_delete)
Ok, I created a helper function that contains both deletes and separated from the API call so that any other function can call it. We can just have the access check happen at the beginning of the API call function before calling the helper that does the actual deleting.

2021-04-23 05:10 UTC, ecaoile commented on api/account_api.py
> -    return minutes_diff
kthx

2021-04-23 05:10 UTC, ecaoile commented on api/auth.py
> +            status_code=403, detail=f"E-mail or password is invalid!")
+2

2021-04-30 00:38 UTC, jtuckerk approved these changes

2021-04-30 00:39 UTC, merged