Links and copy
HF-RapidResponse/volunteer-portal pull request #37
Opened 2020-11-03 20:59 UTC by jtuckerk

updating some minor copy and links changes

2020-11-03 21:03 UTC, jtuckerk commented
waiting on the home page copy for the donation card and an image for this PR

2020-11-04 01:10 UTC, ecaoile requested changes
>

2020-11-04 01:10 UTC, ecaoile commented on client/src/components/About.js
> +        <section className="about-section text-center"> <p
Looks like the p tag is missing a >

2020-11-04 01:11 UTC, ecaoile approved these changes
Nm, I lied. It's fine.

2020-11-05 05:05 UTC, merged