Enable multiple environments with different databases
HF-RapidResponse/volunteer-portal pull request #65
Opened 2020-11-21 18:23 UTC by adamfortuna

**🛑 This is still a work in progress. Do not merge, but feedback/collaboration is welcome in the meantime! 🛑**

### Goals

- Allow for all data currently used by the volunteer portal to be accessed via a local database
- Create a setup script to create and populate a local database to enable development without production database access

2020-12-02 22:50 UTC, jtuckerk commented on api/settings.py
> +    db_pass = secret_client.access_secret_version(request={"name": secret_path}).payload.data.decode('UTF-8')
It'd be nice if this could be skipped if a password is supplied so this could work fully offline/without any hf GCP permissions.
I know this isn't done so don't worry about responding, but this probably won't be the last comment on incomplete code.

2020-12-02 22:50 UTC, jtuckerk commented on api/models/volunteer_event.py
> +                                self.event_uuid, self.event_external_id, self.name)
I like this organization quite a bit

2020-12-02 22:50 UTC, jtuckerk commented on api/api.py
> +    return db.query(VolunteerRole).all()
so the sqlalchemy base models are autoconverted to pydantic models? that's pretty neat!

I'm wondering if we could/would want to try to combine the schemas and models so we only have a single model/schema. I'm concerned about the complexity of this as a volunteer project. It might be a more complicated base class, but I'm hoping it'd simplify additions and debugging. I'm imagining having a mismatch somewhere in the schema->model->db chain could be really annoying to debug.

with this setup I'm imagining we could still have additional schemas defined for endpoints from which we only want to serve a subset of fields.

2020-12-04 00:24 UTC, jtuckerk commented on api/settings.py
> +    db_pass = secret_client.access_secret_version(request={"name": secret_path}).payload.data.decode('UTF-8')
ah I think I misunderstood this on the first go around. There was no generator supplied in the yaml so it was breaking there but I see now I can specify the url generator to use either local or remote in the yaml

2020-12-04 02:41 UTC, Calvinxc1 commented
I added a tweak that'll give us some space to autoload postgres for our needs using docker-compose, it's in the postgres folder. One can just run `docker-compose up -d` in that folder (assuming docker-compose is [installed](https://docs.docker.com/compose/install/)) and it'll start up a containerized Postgres instance. We can make changes to the `Dockerfile` in that directory to set up things like the schema and whatnot so that anyone using this has their Postgres ready and waiting for them right out of the gate.

2020-12-04 05:40 UTC, jtuckerk commented on api/api.py
> +    return db.query(VolunteerRole).all()
> I added a tweak that'll let us autoload Postgres for our needs using docker-compose, it's in the `/postgres` folder. One can just run `docker-compose up -d` in that folder (assuming docker-compose is [installed](https://docs.docker.com/compose/install/)) and it'll start up a containerized Postgres instance. The existing bootstrap approach works just fine for loading the test data, though we may want to look at getting a fully pre-initialized container with the test data already in it, ideally.

Nice! I like moving towards dockerizing everything

How easy is it to define the test data to pre-initialize the db with? I like the set up now since, to me, editiing the python to add rows or edit the schema is intuitive, and also might means if people want to use fake data for testing theyve already written those util functions

2020-12-08 04:51 UTC, jtuckerk commented
I've rebased this change onto the development branch.

I haven't had the time I've wanted to get this fully spruced up to merge into develop. I think it is getting close to at least unblock people for more convenient local development.

The main piece that I think needs to be finished before we can merge this into develop is the tests. Im uncertain about some of the modules are set up and the dependencies referenced. I mostly have used python with bazel to manage dependencies and feel a bit out of my depth on this. @Calvinxc1 or @trippersham if either of you have opinions about how this should be done, please chime in

2020-12-13 19:45 UTC, adamfortuna commented on api/api.py
> +    return db.query(VolunteerRole).all()
> so the sqlalchemy base models are autoconverted to pydantic models? that's pretty neat!

Yep! It duck types the passed in object as whatever the schema is and converts it. I was surprised when it worked to be honest haha.

> I'm wondering if we could/would want to try to combine the schemas and models so we only have a single model/schema. I'm concerned about the complexity of this as a volunteer project. It might be a more complicated base class, but I'm hoping it'd simplify additions and debugging. I'm imagining having a mismatch somewhere in the schema->model->db chain could be really annoying to debug.

That is a concern for sure. There are some libraries that auto-convert from a model to a schema like [pydantic-sqlalchemy](https://github.com/tiangolo/pydantic-sqlalchemy). Those would convert everything, then we'd overwrite everything that's renamed for the front-end.

> with this setup I'm imagining we could still have additional schemas defined for endpoints from which we only want to serve a subset of fields.

2020-12-13 19:45 UTC, adamfortuna commented
> I added a tweak that'll let us autoload Postgres for our needs using docker-compose, it's in the `/postgres` folder. One can just run `docker-compose up -d` in that folder (assuming docker-compose is [installed](https://docs.docker.com/compose/install/)) and it'll start up a containerized Postgres instance. The existing bootstrap approach works just fine for loading the test data, though we may want to look at getting a fully pre-initialized container with the test data already in it, ideally.

Ohh nice! I'm looking forward to giving that a try.

2020-12-16 00:44 UTC, Calvinxc1 commented
Ok, just merged a new docker setup. You should be able to do a `docker-compose build` followed by a `docker-compose up -d` to run the Postgres database. It'll be accessible on the same port that it is by default (5432). Also adminer is running at port 8080 so you have a GUI interface to explore the database. Enjoy!

2020-12-22 14:45 UTC, Calvinxc1 commented
Getting the following when I try to run `docker-compose build` on the new code:
```
Step 6/6 : RUN npm run build
 ---> Running in e17d1234133e

> volunteer-portal@0.5.0 build /srv/client
> react-scripts build

Creating an optimized production build...
Failed to compile.

./src/styles/base.scss
Error: Missing binding /srv/client/node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 14.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! volunteer-portal@0.5.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the volunteer-portal@0.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-22T14_40_40_311Z-debug.log
```

2020-12-29 22:42 UTC, adamfortuna commented
> Getting the following when I try to run `docker-compose build` on the new code:

Hrm, that's a weird one. I just tried clearing all of my docker containers and running a `docker-compose build` from scratch and it's not happening. What OS are you using? I'm wondering if this is a Mac vs Windows issue. Reading through [this article](https://jdlm.info/articles/2019/09/06/lessons-building-node-app-docker.html) on Docker makes me think there's going to be some additional fixes we'll need to add to Windows if that's the case in order to map users. Hopefully it's something more simple though.

2020-12-29 22:48 UTC, Calvinxc1 commented
> > Getting the following when I try to run `docker-compose build` on the new code:
> 
> Hrm, that's a weird one. I just tried clearing all of my docker containers and running a `docker-compose build` from scratch and it's not happening. What OS are you using? I'm wondering if this is a Mac vs Windows issue. Reading through [this article](https://jdlm.info/articles/2019/09/06/lessons-building-node-app-docker.html) on Docker makes me think there's going to be some additional fixes we'll need to add to Windows if that's the case in order to map users. Hopefully it's something more simple though.

Linux ;-)

2020-12-29 22:51 UTC, adamfortuna commented
> Linux ;-)

Back to the drawing board. 😅

2021-01-12 09:07 UTC, jtuckerk requested changes
I think we're pretty close to being good enough to merge this with develop.

It looks like this PR reverts some changes. I think was happened was a rebase/merge/gitword in  6a4d9bb back onto master. Sorry I should have deleted that branch. the should have be a rebase onto develop

2 PRs to merge to this one:
#76 makes slight changes to the docker configs that I think will same others some frustration
#75 is working, but not thoroughly tested, code for the airtable data pipelines

Some other things that I think we can finish later:

- the data source/sink code is now obsolete, I believe
- editing the db columns will require changes in the models, schemas, pipeline converters, and fake data utils. while this isnt ideal, I dont think it's a blocker.

2021-01-12 09:07 UTC, jtuckerk commented on docker-compose.yml
> +    command: npm run start
Let's do "npm run client"
run start runs from the build directory and requires a rebuild to pull in changes.
"npm run client" will allow changes to be hot reloaded.

When we break out services/compose files for prod vs dev we'll use npm run start in prod there to use the optimized build

2021-01-12 09:07 UTC, jtuckerk commented on Makefile
> +	docker-compose run --rm api ENV=test python bootstrap.py
This wasn't working for me

2021-01-12 09:07 UTC, jtuckerk commented on api/data_sources.py
> +        # iterate over the parameters of the model class
I think this whole file can be deleted, but this section in particular looks like a regression to an older commit

2021-01-12 09:07 UTC, jtuckerk commented on api/deploy-prod-app.sh
> +if [ "$branch_name" = "master" ]; then
this shouldn't be reverted to master

2021-01-12 09:07 UTC, jtuckerk commented on client/deploy-prod-client.sh
> +if [ "$branch_name" = "master" ]; then
This shouldn't be reverted to master

2021-01-13 18:13 UTC, adamfortuna commented on docker-compose.yml
> +    command: npm run start
Sounds like a plan, changing this one.

2021-01-13 18:26 UTC, adamfortuna commented on Makefile
> +	docker-compose run --rm api ENV=test python bootstrap.py
Updated these to use a new test container and updated the makefile.

2021-01-13 18:26 UTC, adamfortuna commented on api/data_sources.py
> +        # iterate over the parameters of the model class
Yeah, I think it can. If we need parts of it, we can move them into the new spots later. Deleting these for now.

2021-01-13 19:57 UTC, adamfortuna commented on api/deploy-prod-app.sh
> +if [ "$branch_name" = "master" ]; then
Good catch!

2021-01-13 19:57 UTC, adamfortuna commented on client/deploy-prod-client.sh
> +if [ "$branch_name" = "master" ]; then
Good catch!

2021-01-14 22:44 UTC, jtuckerk requested changes
I think there are still a bunch of changes in the client that revert a fair bit of work in development

should there be any changes in this PR to the files in client/src? 

The rest of the changes look good tho!

2021-01-14 22:44 UTC, jtuckerk commented on api/api.py
> +    db.add(DonationEmail(email=donationEmail.email))
The old way looked weird. I was surprised it worked. or did it not?

2021-01-14 22:44 UTC, jtuckerk commented on api/schemas/donation_email.py
> +    @validator('email')
Theres a pydantic type we can use to do this validation
`from pydantic import EmailStr`

2021-01-14 22:44 UTC, jtuckerk commented on client/src/App.js
>  import React from 'react';
I believe this was an unintended revert too, along with all of the other changes in client/src I think

2021-01-14 22:47 UTC, jtuckerk commented on docker-compose.yml
> +    - api
can we add api-test here. IIUC this only affects the order but wont spin up both api and api-test at the same time when the proxy reloads

2021-01-20 05:26 UTC, jtuckerk commented on docker-compose.yml
> +    - api
Nvm, with the PR i have  out this may be obsolete

2021-01-21 08:47 UTC, jtuckerk commented
changes from #75, #78 and #80 all merged into and on top of this and appear to be working in branch revert+docker+db_pipeline

2021-01-21 17:48 UTC, adamfortuna commented on api/api.py
> +    db.add(DonationEmail(email=donationEmail.email))
I haven't been able to validate the previous way works, but I know the new way works at least. I wanted to make it cleaner, but gave up eventually and went the less-pretty way.

2021-01-21 17:57 UTC, adamfortuna commented on client/src/App.js
>  import React from 'react';
Off, yeah there shouldn't be any changes in Client other than cleaning up an API request path or two to no longer include a trailing slash. Must've had conflicts during a merage. I'll replace that.

2021-01-21 21:11 UTC, jtuckerk approved these changes

2021-01-23 19:41 UTC, merged