Authentication POC
HF-RapidResponse/volunteer-portal pull request #71
Opened 2020-12-14 20:58 UTC by trippersham

2020-12-15 22:28 UTC, adamfortuna commented on api/api.py
> +    user = await oauth.google.parse_id_token(request, token)
This is super concise - I like it! Are you thinking we'd also have a `user` model in our database that's created/loaded here based on the auth info? A user has many authentications kind of setup?

2021-02-06 20:57 UTC, jtuckerk requested changes
Looks good! I haven't poked around yet and want to do that before final approval but wanted to get the client IDs and secrets set up with secret manager first if possible. Do you have keys from the HF GCP project and the github org or did you use your own for testing? 

I can work with you to get those created for test and dev. I'm also wondering if we don't need them for dev and can set up a way to do auth locally that we'd use for development and unit tests.

I think there are a few files/changes that got reverted/weren't fast forwarded to the current state of dev. I've added comments inline for those

2021-02-06 20:57 UTC, jtuckerk commented on .gitignore
> +api/config.yaml
I think we should just keep config.yaml in git. Since we won't be putting password directly in any config files (using google secret manager instead) I think it'll just save a step of having everyone copy over the example config.

2021-02-06 20:57 UTC, jtuckerk commented on .gitignore
> +api/config.yaml
Here's an example of how the secret manager is used for the DB password. https://github.com/HF-RapidResponse/volunteer-portal/blob/develop/api/settings.py#L21

We can store the client ID and secret in separate 'secrets' and have a pair for prod and a pair for dev and just use all the same code paths, or if we want the dev version to work without internet/GCP project permissions set up (Slight preference because of this) we can have it toggle-able from the config like Adam did with the db_url/secret generators

2021-02-06 20:57 UTC, jtuckerk commented on api/Makefile
> +.PHONY: test
Can we delete this file? and move anything not covered by the current makefile at the project root have docker version of anything that may be missing if necessary

2021-02-06 20:57 UTC, jtuckerk commented on api/data_sources.py
> +from pydantic import BaseModel
Can we keep this file deleted?

2021-02-06 20:57 UTC, jtuckerk commented on api/models/personal_donation_link_request.py
> +from models.base import Base
Keep deleted as well?

2021-02-06 20:57 UTC, jtuckerk commented on api/requirements.txt
> +sqlalchemy-utils
I think (not positive) this is no longer needed)

2021-02-06 20:57 UTC, jtuckerk commented on api/schemas/personal_donation_link_request.py
> +from pydantic import BaseModel, EmailStr
delete this file?

2021-02-06 20:57 UTC, jtuckerk commented on api/settings.py
> +Connections = create_connections(db_url_generators, Config['databases'])
with the updated config setup only a single DB is expected so this has been flattened and I think this is just a missed fast forward/unwanted reversion

2021-02-06 20:57 UTC, jtuckerk commented on api/tests/todo_test_data_sources.py
> +import pytest
delete this file?

2021-02-06 20:57 UTC, jtuckerk commented on client/package.json
> +  }
TODO for me: Check this doesnt break things once I'm set up with IDs and secrets

2021-02-06 20:57 UTC, jtuckerk commented on docs/auth_security.md
> +# Auth & Security
docs 
![image](https://user-images.githubusercontent.com/8518434/107129296-6c837300-6892-11eb-9dbb-e1ac023ebfeb.png)

2021-02-06 20:57 UTC, jtuckerk commented on api/auth.py
> +    current_user = Authorize.get_jwt_subject()
I'm struggling to find the docs on this. Will this be a auth client specific identifier?

2021-02-08 16:47 UTC, trippersham commented on api/settings.py
> +Connections = create_connections(db_url_generators, Config['databases'])
This is actually for the new config.yaml structure that pulls the DB settings into a 'databases' key. However please check to make sure what lives under that subkey is what you're expecting with the new flattened structure within it.

2021-02-08 16:52 UTC, trippersham commented on api/auth.py
> +    current_user = Authorize.get_jwt_subject()
[Here](https://indominusbyte.github.io/fastapi-jwt-auth/) are the docs for this: I will include them in our auth security docs

2021-02-10 20:05 UTC, jtuckerk approved these changes
looks good, just some notes on your docker commands. The make test command will take multiple minutes so I want to be really sure that build step is necessary before we check it in

2021-02-10 20:05 UTC, jtuckerk commented on Makefile
> +	docker-compose $(TEST) build --no-cache api db
does the auth stuff need to be rebuilt to be reconfigured? rebuilding the api is a bummer since its so slow :(

2021-02-10 20:05 UTC, jtuckerk commented on Makefile
> +	docker-compose $(TEST) build --no-cache api db
actually on second thought, I think a "down" and "up" should work even if it does have to restart. I've tested it by removing this build line and running:
`docker-compose up`, then `make test` and saw that it failed, then ran `docker-compose down` followed by `make test`. so I think we could replace that line with just docker-compose down and hopefully save a lot of waiting, especially when people are running make test multiple times in a row

and then with respect to the above warning, just a docker-compose down and docker-compose up should bring back the full development environment.

2021-02-10 20:05 UTC, jtuckerk commented on api/auth.py
> +    current_user = Authorize.get_jwt_subject()
thanks

2021-02-10 20:05 UTC, jtuckerk commented on api/settings.py
> +Connections = create_connections(db_url_generators, Config['databases'])
the  structure within looks good

2021-02-10 20:05 UTC, jtuckerk commented on docs/dependencies.md
> +* `make recreate-api`
same comment from above. i think docker-compose down followed by an up should fix all of this. please let me know if I'm missing something/that only works in simple cases!

2021-02-10 22:01 UTC, merged