Tucker airtable data pipeline
HF-RapidResponse/volunteer-portal pull request #75
Opened 2021-01-09 22:29 UTC by jtuckerk

Creating a airtable table syncing pipeline.
So far this is only set up for events

todo:

- [ ] initiatives
- [ ] roles
- [ ] more testing

2021-01-13 20:38 UTC, adamfortuna requested changes
Few minor recommendations, but looks good to me!

2021-01-13 20:38 UTC, adamfortuna commented on api/api.py
> +def SyncRunner(db, sync_fn) -> str:
What would you think about moving from here down to a different file? I saw @trippersham did something like that in the auth branch, ( https://github.com/HF-RapidResponse/volunteer-portal/blob/auth_poc/api/api.py#L11 ) which I think would be a good way to add additional routes without putting everything in api.py.

2021-01-13 20:38 UTC, adamfortuna commented on api/db_sync_pipelines/pipelines.py
> +  table_key = 'appXC8UaNIuMXpnGB'
Do you think we could split these out into a settings variable? It'd be nice to be able to test this using a copy of the Airtable without having access to production.

2021-01-13 20:38 UTC, adamfortuna commented on api/models/volunteer_role.py
> +    responsibilities = Column('responsibilities_and_duties', Text)
lol, good catch!

2021-01-13 20:38 UTC, adamfortuna commented on api/models/initiative.py
> +    db_last_modified = Column('db_last_modified', DateTime, nullable=False)
This is 100% personal preference, but I always call this column `updated_at`. It looks like there's a way to automatically update this column too: https://stackoverflow.com/questions/13370317/sqlalchemy-default-datetime

```
from sqlalchemy.sql import func
updated_at = Column('updated_at', DateTime, onupdate=func.now())
```

Could be one wy to slim down a little code.
With that, SQLAlchemy will automatically update that column's value whenever it changes.

2021-01-13 20:38 UTC, adamfortuna commented on api/tests/db_sync_pipelines/events_example_response.json
> +        "email": "tom@tomjeffreyinnovations.com",
Might want to remove these emails, and change some names to use `@example.com` if they're real ones.

2021-01-13 20:38 UTC, adamfortuna commented on api/tests/db_sync_pipelines/events_example_response.json
> +        "email": "tom@tomjeffreyinnovations.com",
Might want to remove these emails, and change some names to use `@example.com` if they're real ones.

2021-01-14 06:35 UTC, jtuckerk commented on api/db_sync_pipelines/pipelines.py
> +  table_key = 'appXC8UaNIuMXpnGB'
I do think it's something we should look into, but maybe further down the road.
I'm not sure I want to spin up a test version of the airtable. I don't see much benefit since any changes to the prod tables wouldn't be caught by those tests. (the airtable team is looking into how to prevent changes to the tables and columns we care about.)

It doesn't look like there are very fine grained permissions within airtable so giving permissions to a view or even a "synced" version of the table would open up all of airtable ~ish. ish: If we can change those table keys ^ we could keep the new ones private (should have kept them private to start) and only expose the global key (which we'd have to verify doesn't grant access to downloading individual table keys, or anything else we dont want)

option I like the most would be while syncing, dump a subset the json response to a cloud storage file and use something like the FakeAirtableLoader ive used in the tests to serve as a dev/test replacement for airtable

2021-01-14 06:38 UTC, jtuckerk commented on api/tests/db_sync_pipelines/events_example_response.json
> +        "email": "tom@tomjeffreyinnovations.com",
ah good catch!

2021-01-14 06:38 UTC, jtuckerk commented on api/tests/db_sync_pipelines/events_example_response.json
> +        "email": "tom@tomjeffreyinnovations.com",
thanks!

2021-01-14 06:45 UTC, jtuckerk commented on api/models/initiative.py
> +    db_last_modified = Column('db_last_modified', DateTime, nullable=False)
oh yeah much better. thanks!

2021-01-14 22:06 UTC, jtuckerk commented on api/api.py
> +def SyncRunner(db, sync_fn) -> str:
done!

2021-01-14 22:07 UTC, jtuckerk commented on api/tests/db_sync_pipelines/events_example_response.json
> +        "email": "tom@tomjeffreyinnovations.com",
I'll rebase this and force push the changes before we merge this just to remove that from the commit graph, but wanted to leave you with the diffs for now.

2021-01-15 21:11 UTC, jtuckerk commented on api/models/volunteer_role.py
> +    responsibilities = Column('responsibilities_and_duties', Text)
:)

2021-02-05 18:16 UTC, trippersham commented on api/db_sync_pipelines/airtable_event_converter.py
> +      'start_datetime': ParseTimestamp,
I like that these are defined functions (as opposed to the lambdas I was using previously). I feel like it will be good to have a library of these common "custom" transforms when we have other data sources in the pilot even if we need to support truly one-off transforms in the future.

2021-02-05 18:16 UTC, trippersham commented on api/db_sync_pipelines/airtable_sync.py
> +    all_records = list(GetAndConvertAirtableRecords(
GetAndConvertAirtableRecords is a generator but you immediately convert it to a list to then use in a loop. Unless I misunderstand generators (very possible) you're losing the performance benefits of using the generator in the first place; why not just pass the generator straight into the loop?

2021-02-05 18:16 UTC, trippersham commented on api/db_sync_pipelines/airtable_sync.py
> +    all_records = list(GetAndConvertAirtableRecords(
Digging through the calls: why are you using a generator? There's only one network call and you get a list of all of the airtable rows (I'm assuming the memory usage of that list is not substantially different than the converted rows).

2021-02-05 18:16 UTC, trippersham commented on api/db_sync_pipelines/airtable_sync.py
> +    query = db.query(db_model.external_id)
This creates a hard requirement that all external data sources need to have a persistent unique ID associated with each row. Not sure if that's a good or bad requirement, but something we should keep in mind for the future.

2021-02-05 18:16 UTC, trippersham commented on api/db_sync_pipelines/airtable_sync.py
> +    result = query.first()
This assumes those records can only be modified by the sync pipeline. We don't have a way to edit these records from the UI today but we probably will in the future (even if we don't allow you to edit/override this data, we may have other fields like "users_with_this_role" that are updated on our side). It may be safer/more future-proofed to keep a separate updated column that only pertains to the sync pipeline.

2021-02-05 18:16 UTC, trippersham commented on api/db_sync_pipelines/airtable_sync.py
> +        elif NeedsUpdate(record, latest_sync_run):
Smart, I like this

2021-02-05 18:16 UTC, trippersham commented on api/db_sync_pipelines/airtable_sync.py
> +    airtable_records = set([record.external_id for record in all_records])
slight suggestion to change these variable names to "_ids" so new folks don't think the contents of "new_records" and "deleted_records" are the same types

2021-02-05 18:16 UTC, trippersham commented on api/db_sync_pipelines/airtable_sync.py
> +                db_model.external_id == local_record.external_id).delete()
If/when we have other data stored on those records that doesn't come from this external source, this will be overzealous. Fine for now, but we should probably do an upsert as opposed to a delete and replace.

2021-02-05 18:16 UTC, trippersham commented on api/db_sync_pipelines/airtable_sync.py
> +def UpdateRecordsAsDeleted(to_delete, db, db_model):
Love a good soft delete

2021-02-05 18:16 UTC, trippersham commented on api/db_sync_pipelines/airtable_sync.py
> +class AirtableLoader:
What's the rationale for having these functions live outside of the class? Making testing easier so we don't need to use a mock?

2021-02-05 18:16 UTC, trippersham commented on api/models/initiative.py
>  class Initiative(Base):
What do you think about creating a subclass of Base that handles things like "external_id", "is_deleted", and "updated_at" (esp. depending on your thoughts on my comment on GetLatestSyncRun)? Will make it harder to accidentally forget those fields that are primarily used by the sync pipeline.

2021-02-06 21:02 UTC, jtuckerk commented on api/db_sync_pipelines/airtable_event_converter.py
> +      'start_datetime': ParseTimestamp,
Yeah, I thought about pulling these out fully to a separate utils file, but since theyre so simple and the only real meat of the function is an airtable date format,  I left them in an airtable file.

2021-02-06 21:04 UTC, jtuckerk commented on api/db_sync_pipelines/airtable_event_converter.py
> +      'start_datetime': ParseTimestamp,
I'm leaning towards leaving it for now but if you feel strongly about breaking it out now, let me know

2021-02-06 22:46 UTC, jtuckerk reviewed
great feedback thank you!

2021-02-06 22:46 UTC, jtuckerk commented on api/db_sync_pipelines/airtable_sync.py
> +class AirtableLoader:
at some point in my career someone who cares a lot more about these sorts of things than I do pointed out that if a function doesnt operate on an instance's state it shouldn't be defined within the class. It avoids having to use self in the definition and the call which i guess is cleaner.
~time passes and other comments got me thinking~
I've made these part of the APIResponseConverter file, but still not a part of the class for the same reason

2021-02-06 22:46 UTC, jtuckerk commented on api/db_sync_pipelines/airtable_sync.py
> +    all_records = list(GetAndConvertAirtableRecords(
I probably put that in for debugging and accidentally left it. It's now removed.
I was just using a generator more for style and simplicity to avoid declaring a list and appending. Also possible I borrowed code from something that did some paging.
I'm now using list comprehension which may be bad style, idk.

2021-02-06 22:46 UTC, jtuckerk commented on api/db_sync_pipelines/airtable_sync.py
> +        elif NeedsUpdate(record, latest_sync_run):
May be overkill for some of these smaller tables, but if we ever decide to pull all the volunteer records in, this gives a big speedup.

2021-02-06 22:46 UTC, jtuckerk commented on api/db_sync_pipelines/airtable_sync.py
> +    airtable_records = set([record.external_id for record in all_records])
good call

2021-02-06 22:46 UTC, jtuckerk commented on api/db_sync_pipelines/airtable_event_converter.py
> +      'start_datetime': ParseTimestamp,
moved these to the api_response_converter file since the now timestamp is generic and airtable uses the ISO standard  (also added this and other comments to a review to avoid individual notifications for each comment I make, sorry if it formats weird and any previous annoyance)

2021-02-06 22:46 UTC, jtuckerk commented on api/db_sync_pipelines/airtable_sync.py
> +    query = db.query(db_model.external_id)
For the data centralization work I was doing I was creating a separate syncing pipeline for each platform. definitely ended up being a lot of code reused, but then you dont have to worry as much about things like that. Since this is just the airtable syncer and it seems like we're moving away from the possibility of using more external platforms in the near to mid term I'm not too concerned
good to keep in mind for sure tho

2021-02-06 22:46 UTC, jtuckerk commented on api/db_sync_pipelines/airtable_sync.py
> +    result = query.first()
hmmm good point.
How do you feel about leaving it as is and just moving off airtable once we have a portal UI for updating them? The idea of having 2 sources for 1 db doesn't seem fun. If we do leave this field to be updated by the UI or the pipeline then it would effectively give the UI priority since anything changed with the UI later would cause earlier Airtable changes to be ignored. which I think would be fine behavior, tho again, not excited about dealing with figuring that out completely. 20% chance I'm ignoring other good reasons to change it and am just coming up with reasons not to do any more work.

2021-02-06 22:46 UTC, jtuckerk commented on api/db_sync_pipelines/airtable_sync.py
> +                db_model.external_id == local_record.external_id).delete()
yeah,  I didnt like this. I banged my head on it for a while and didnt feel like I was getting the type of solution I thought should exist. I may not have searched "upsert" hmmm. but either way I'm still a bit wary of having multiple sources for a single record

2021-02-06 22:46 UTC, jtuckerk commented on api/models/initiative.py
>  class Initiative(Base):
ooh yeah

2021-02-06 22:46 UTC, jtuckerk commented on api/models/initiative.py
>  class Initiative(Base):
done

2021-02-08 20:37 UTC, trippersham approved these changes

2021-02-09 20:40 UTC, merged