removing about route and changing social share image
HF-RapidResponse/volunteer-portal pull request #77
Opened 2021-01-15 06:56 UTC by ecaoile

These are urgent HF requests. Not too much work, but I can't test the social share change until the image is deployed on a non-localhost environment.

2021-01-15 16:13 UTC, trippersham requested changes
@ecaoile I'm still seeing the old image locally on the branch with `npm run client` and `npm start`; do I need to build differently or something to see the correct image?

![Screen Shot 2021-01-15 at 8 09 17 AM](https://user-images.githubusercontent.com/5006658/104750865-7f7aab80-5709-11eb-999b-414fcf197224.png)

2021-01-15 16:23 UTC, ecaoile commented
> @ecaoile I'm still seeing the old image locally on the branch with `npm run client` and `npm start`; do I need to build differently or something to see the correct image?
> 
> ![Screen Shot 2021-01-15 at 8 09 17 AM](https://user-images.githubusercontent.com/5006658/104750865-7f7aab80-5709-11eb-999b-414fcf197224.png)

I think it’s because the share link is pointing to prod. React-share doesn’t seem to like local host URLs, so I can’t test it that way. If you could deploy to dev and temporarily change the share URL to dev, you can test it out

2021-01-19 16:21 UTC, trippersham approved these changes

2021-01-19 16:22 UTC, trippersham commented
Approving so we can deploy and ensure it works, thanks @ecaoile!

2021-01-19 16:22 UTC, merged