Add upcoming events to /calendar
HF-RapidResponse/volunteer-portal pull request #86
Opened 2021-02-18 07:48 UTC by vai0

## Summary
This adds an "Upcoming Events" section to /calendar.

2021-02-19 05:24 UTC, ecaoile requested changes

2021-02-19 05:24 UTC, ecaoile commented on client/src/components/Calendar.js
> +            <Col xs={12} lg={8} className="shadow-card" key={uuid}>
React is yelling about unique keys on line 47. I figured uuid would be unique enough, but I guess it's being used elsewhere, I added the index to map and then changed the key to uuid + 'cal event ' + index. That seemed to work.

Other than that, it looks fine.

2021-02-21 01:19 UTC, ecaoile approved these changes

2021-02-21 19:37 UTC, trippersham approved these changes

2021-02-21 19:38 UTC, trippersham commented
@vai0 now that you're gotten a few approvals, feel free to merge to develop when you get the chance!

2021-02-22 07:56 UTC, merged