Implement account creation with CRUD functionality (oauth and regular) DO NOT MERGE YET!
HF-RapidResponse/volunteer-portal pull request #95
Opened 2021-02-26 01:35 UTC by ecaoile

This is pretty much the entire accounts feature. Users can create accounts and manage their settings.

2021-03-09 17:34 UTC, jtuckerk requested changes
This is looking super good! I did a mostly superficial review so far and will take another pass in the next day or 2 to go through the code more closely

2021-03-09 17:34 UTC, jtuckerk commented on client/src/components/Header/index.js
> +  const mainLinks = [
The new nav configuration is a bit squeezed on the left and theres a big gap on the right in a 1920x1080 screen
![image](https://user-images.githubusercontent.com/8518434/110505031-c5ca0680-80cb-11eb-94e6-5919af8aa5ac.png)

2021-03-09 17:34 UTC, jtuckerk commented on client/src/components/Register.js
> +                'Please enter a password between 6 and 20 characters long with at least 1 letter, 1 nuumber, and 1 special character.'
1 nuumber

2021-03-09 17:34 UTC, jtuckerk commented on client/src/components/Register.js
> +                'Please enter a password between 6 and 20 characters long with at least 1 letter, 1 nuumber, and 1 special character.'
I'm getting this error with pass.1234 which I think should be valid

*time passes*

turns out I hadn't set up the db with the new tables. Could we separate this error from backend 500s in case we do experience 500s we dont want people thinking it's their faults

*more time passes* 

I believe I've got the backend setup properly and am not seeing any backend errors, but am still getting errors for  pass.1234 - also the check marks tell me its all good and the error message contradicts that. I think you brought that up in the meeting as an issue you were aware of.

2021-03-09 17:34 UTC, jtuckerk commented on api/models/account.py
> +    UniqueConstraint(email, username, name='unique_acct_emails_usernames')
This is redundant right? since the email and username are already independently unique? or does this somehow enforce that usernames can't be emails that already exist as emails?

2021-03-09 17:34 UTC, jtuckerk commented on api/models/account.py
> +class Account(Base):
before merging can you run `make db-reset-all-from-python` (and then add a new commit) this will update `db/data/dev/data.development.sql` and `db/data/test/data.test.sql` so the development DB is set up with all the proper tables when it is rebuilt

2021-03-09 17:34 UTC, jtuckerk commented on client/src/components/Header/MainMenu.js
> +        <NavDropdown.Divider
I like this dropdown it looks nice and streamlines navigation, but I'm worried it will be really squeezed with all of our fairly long initiative names.

2021-03-09 17:34 UTC, jtuckerk commented on client/src/components/Register.js
> +          <GoogleOAuthButton />
Can this be at the top? I didnt see it and started to fill out my info even though I would have just preferred to use google in the first place if I had seen it.

2021-03-09 17:34 UTC, jtuckerk commented on client/src/components/Account/AccountNav.js
> +import React, { useState } from 'react';
The account/profile flows are all so great!

2021-03-09 17:34 UTC, jtuckerk commented on client/src/components/Account/Profile.js
> +            <Form.Switch
Can we make email default to not showing on the profile? I doubt people want to display their emails by default, and they may not notice it is checked to display

2021-03-09 17:34 UTC, jtuckerk commented on api/models/account.py
> +    password = Column('password', Text, nullable=True)
Can we add a comment here noting that passwords are encrypted and a pointer to that logic?

2021-03-09 17:34 UTC, jtuckerk commented on api/models/settings.py
> +class Settings(Base):
Could we maybe call this AccountSettings? just in case we have some other types of settings? I've been tossing around some ideas for an Admin api that might need it's own settings. we can/should call those adminSettings, but it might still save some confusion

2021-03-09 17:37 UTC, jtuckerk commented on api/api.py
> +CLIENT_ID = "899853639312-rluooarpraulr242vuvfqejefmg1ii8d.apps.googleusercontent.com"
can this be removed?

2021-03-10 00:55 UTC, ecaoile commented on api/models/account.py
> +    UniqueConstraint(email, username, name='unique_acct_emails_usernames')
They should be unique, but the constraint doesn't seem to work. I added constraints here and in the SQL file, but neither of them did nothing. Maybe I'm misunderstanding how UniqueConstraint is supposed to work. I ended up having to write in checks on the API to check for existing usernames and emails

2021-03-10 00:58 UTC, ecaoile commented on client/src/components/Header/MainMenu.js
> +        <NavDropdown.Divider
Do you want to get rid of it then?

2021-03-10 01:02 UTC, ecaoile commented on client/src/components/Register.js
> +          <GoogleOAuthButton />
I suppose we could, but I think I'm used to seeing it at the bottom of forms. Have you seen it anywhere at the top? I suppose it might make sense to have it at the time for register at least, but I dunno...hmm...

2021-03-10 01:07 UTC, ecaoile commented on client/src/components/Header/index.js
> +  const mainLinks = [
We can center it with ml-auto. How does this look?
![image](https://user-images.githubusercontent.com/34725510/110559910-e90baa80-80f9-11eb-8103-22e3ce81c8eb.png)

2021-03-10 05:01 UTC, ecaoile commented on client/src/components/Header/index.js
> +  const mainLinks = [
Actually, I think the intent from the UI/UX folks was there to be a gap at least at bigger resolutions. We could probably add a little more margin-left, though.

2021-03-10 05:43 UTC, ecaoile commented on client/src/components/Register.js
> +                'Please enter a password between 6 and 20 characters long with at least 1 letter, 1 nuumber, and 1 special character.'
Ok, it was a combination of things. The regex for password validation was a little off: it didn't include periods or a few other characters. Oops. Also figured out how to disable the green checkmark when I don't need it. Wish Bootstrap didn't show the valid when an invalid prompt was present. Anyway, fix incoming...

2021-03-10 07:52 UTC, ecaoile commented on client/src/components/Register.js
> +                'Please enter a password between 6 and 20 characters long with at least 1 letter, 1 nuumber, and 1 special character.'
Nm, I kinda lied. Password validation is busted and always shows valid feedback with any character. I dunno why.

2021-03-10 08:10 UTC, ecaoile commented on client/src/components/Header/index.js
> +  const mainLinks = [
added a tiny bit of spacing:
![image](https://user-images.githubusercontent.com/34725510/110597130-04e07200-8135-11eb-8b19-39d6a33f7af7.png)

2021-03-10 08:12 UTC, ecaoile commented on client/src/components/Register.js
> +                'Please enter a password between 6 and 20 characters long with at least 1 letter, 1 nuumber, and 1 special character.'
fixed

2021-03-10 08:13 UTC, ecaoile commented on client/src/components/Account/AccountNav.js
> +import React, { useState } from 'react';
Thanks, I aim to please!

2021-03-10 08:14 UTC, ecaoile commented on api/api.py
> +CLIENT_ID = "899853639312-rluooarpraulr242vuvfqejefmg1ii8d.apps.googleusercontent.com"
Yes. Fixed.

2021-03-10 08:14 UTC, ecaoile commented on api/models/settings.py
> +class Settings(Base):
changed to AccountSettings

2021-03-10 08:17 UTC, ecaoile commented on client/src/components/Account/Profile.js
> +            <Form.Switch
fixed

2021-03-10 08:37 UTC, ecaoile commented on api/models/account.py
> +class Account(Base):
That command doesn't work.
`
make: *** No rule to make target 'db-reset-all-from-python'.  Stop.`

2021-03-10 08:43 UTC, ecaoile commented on api/config.yaml
> +      password: humanity-forward_hf-portal_psql-db_admin
@jtuckerk This build is now busted after adding these config.yaml

2021-03-10 17:09 UTC, ecaoile commented on api/settings.py
> +def generate_hf_secret_db_address(connection) -> str:
@jtuckerk this might have broken it too

2021-03-10 18:54 UTC, jtuckerk reviewed
I really dont like how github structures these reviews. It seems like I have to submit this before responding to your responses? more comments coming in a sec

2021-03-10 18:54 UTC, jtuckerk commented on api/models/account.py
> +    roles = Column('roles', ARRAY(String), default=[], nullable=False)
Is the plan to just have these be strings users can add themselves? or do we want roles to be tied to more functionality

2021-03-10 18:54 UTC, jtuckerk commented on api/api.py
> +def get_all_accounts(db: Session = Depends(get_db)):
Dont forget to delete this! We need an admin API to authorize stuff like this

2021-03-10 18:54 UTC, jtuckerk commented on api/api.py
> +    if existing_acct is not None:
I'm looking into the db unique constraint stuff and I think we can get the DB to check the uniqueness of emails itself. tho this might be an easier way than trying to handle the error from the db.

I've sent PR#104 with tests and things related to this

2021-03-10 18:54 UTC, jtuckerk commented on api/schemas/account.py
> +    password: Optional[Text]
I think we'll want to exclude this from the schema

2021-03-10 18:56 UTC, jtuckerk commented on api/models/account.py
> +    UniqueConstraint(email, username, name='unique_acct_emails_usernames')
I've added some other comments about this and PR#104. I still dont think the check in api.py is a bad idea, but we will need to do that check for username also so maybe it is easier to just let the db do that check not that (i think) we have a fix for that

2021-03-10 18:57 UTC, jtuckerk commented on client/src/components/Register.js
> +                'Please enter a password between 6 and 20 characters long with at least 1 letter, 1 nuumber, and 1 special character.'
ah I thought I tried an @ symbol. maybe that was one of the other non-special special characters

2021-03-10 18:58 UTC, jtuckerk commented on api/models/account.py
> +class Account(Base):
hmmm that's odd. Did you do `docker-compose down` first? I just did it in PR#104 and it seemed to work as expected

2021-03-10 19:00 UTC, jtuckerk commented on client/src/components/Register.js
> +          <GoogleOAuthButton />
hmm I think youre right, it is usually at the bottom, but it's usually not off the edge so I can still see it, maybe we could have the self account creation fields expand if that's selected?

2021-03-10 19:01 UTC, jtuckerk commented on api/config.yaml
> +      password: humanity-forward_hf-portal_psql-db_admin
ahh heck. I'll look into it

2021-03-11 01:40 UTC, ecaoile commented on api/models/account.py
> +    roles = Column('roles', ARRAY(String), default=[], nullable=False)
I honestly don't know what the intended functionality will be for roles, so I just guessed that we would be able to put them into an array. We might actually have to do something like the initiative_map that I moved to acct settings.

2021-03-11 01:40 UTC, ecaoile commented on api/api.py
> +def get_all_accounts(db: Session = Depends(get_db)):
Oops, yeah, I made that route for testing. We really shouldn't be leaving that open for everyone.

2021-03-11 01:42 UTC, ecaoile commented on api/schemas/account.py
> +    password: Optional[Text]
Wait, if we exclude properties from the schema, are we still able to pass them in to the API?

2021-03-11 02:05 UTC, ecaoile commented on client/src/components/Register.js
> +          <GoogleOAuthButton />
We could have it similar to what I did for the password change where you don't show the new password and retype until someone actually types in. To make it more obvious there's more info to put in, we could add some kind of opacity fade out effect with CSS at the bottom as a preview.

2021-03-11 04:05 UTC, jtuckerk commented
I'm getting "welcome back, Undefined!" when I started up the app. I'm guessing that has something to do with having a token in my browser but the db being blank? This probably wont come up in prod, unless someone forced it, but I'm wondering if its something we should bother preventing
![image](https://user-images.githubusercontent.com/8518434/110733927-d4600d00-81f4-11eb-811e-d7ac8e1fe9e4.png)

2021-03-11 05:38 UTC, ecaoile commented on client/src/components/Header/index.js
> +  const mainLinks = [
Spacing has been pushed, so I'll resolve this too unless you want more.

2021-03-11 05:39 UTC, ecaoile commented on client/src/components/Register.js
> +                'Please enter a password between 6 and 20 characters long with at least 1 letter, 1 nuumber, and 1 special character.'
Yeah, I suck at regex. Anyway, . and @ are both working now.

2021-03-11 05:43 UTC, ecaoile commented
> 
> 
> I'm getting "welcome back, Undefined!" when I started up the app. I'm guessing that has something to do with having a token in my browser but the db being blank? This probably wont come up in prod, unless someone forced it, but I'm wondering if its something we should bother preventing
> ![image](https://user-images.githubusercontent.com/8518434/110733927-d4600d00-81f4-11eb-811e-d7ac8e1fe9e4.png)

Oh, we definitely should be checking for that, though. That shouldn't be too hard to fix. We can just include cookies into the parameter, and if the user doesn't exist in the db, we just remove that cookie and refresh the page.

2021-03-11 07:53 UTC, ecaoile commented on client/src/components/Register.js
> +                'Please enter a password between 6 and 20 characters long with at least 1 letter, 1 nuumber, and 1 special character.'
I fixed the password issue. It was really was regex. Bob Saget, Kelly Clarkson, Ryan Seacrest!

2021-03-14 20:08 UTC, ecaoile commented on client/src/components/Register.js
> +          <GoogleOAuthButton />
moved oauth to top

2021-03-14 20:09 UTC, ecaoile commented on api/api.py
> +def get_all_accounts(db: Session = Depends(get_db)):
commented out

2021-03-14 20:10 UTC, ecaoile commented on api/models/account.py
> +    roles = Column('roles', ARRAY(String), default=[], nullable=False)
Resolving this for now. We can change the prop later if needed

2021-03-14 20:11 UTC, ecaoile commented on api/models/account.py
> +class Account(Base):
It works now.

2021-03-14 21:11 UTC, powell759 commented
Taking a first functional pass - looks fantastic!

Size is a bit fatiguing though; since this is security-critical functionality I'm going take several passes. Would recommended keeping PRs much smaller going forward.

2021-03-14 21:42 UTC, powell759 commented
![image](https://user-images.githubusercontent.com/10932655/111085167-69a02180-84d3-11eb-84c2-77f83f2fb00a.png)

Is it possible to have human-readable name here?

2021-03-14 21:53 UTC, powell759 commented
functional nit:

Password requirements are not enforced by API, run following from console:

```
fetch("http://localhost:8000/api/accounts/", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "application/json;charset=UTF-8",
    "sec-ch-ua": "\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "sec-gpc": "1"
  },
  "referrer": "http://localhost:8000/register",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"username\":\"foo\",\"email\":\"bar@fuzz.com\",\"first_name\":\"test\",\"last_name\":\"tester\",\"password\":\"password\",\"roles\":[]}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```

2021-03-14 22:00 UTC, powell759 commented
Question on API - I'm seeing a "roles" field for account creation requests. If this is for admin/privileges? If so then we'll need restrictions here to prevent privilege escalation.

Example of arbitrary role creation:
```
fetch("http://localhost:8000/api/accounts/", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "application/json;charset=UTF-8",
    "sec-ch-ua": "\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "sec-gpc": "1"
  },
  "referrer": "http://localhost:8000/register",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"username\":\"test1\",\"email\":\"test1@test.com\",\"first_name\":\"test\",\"last_name\":\"tester\",\"password\":\"password\",\"roles\":[\"Test Role\"]}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```

2021-03-14 22:01 UTC, ecaoile commented
> 
> 
> ![image](https://user-images.githubusercontent.com/10932655/111085167-69a02180-84d3-11eb-84c2-77f83f2fb00a.png)
> 
> Is it possible to have human-readable name here?

I think this is sometimes that needs to be changed on the Google end. @trippersham can you change the name?

2021-03-14 22:04 UTC, ecaoile commented
> 
> 
> Question on API - I'm seeing a "roles" field for account creation requests. If this is for admin/privileges? If so then we'll need restrictions here to prevent privilege escalation.
> 
> Example of arbitrary role creation:
> 
> ```
> fetch("http://localhost:8000/api/accounts/", {
>   "headers": {
>     "accept": "application/json, text/plain, */*",
>     "accept-language": "en-US,en;q=0.9",
>     "content-type": "application/json;charset=UTF-8",
>     "sec-ch-ua": "\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\"",
>     "sec-ch-ua-mobile": "?0",
>     "sec-fetch-dest": "empty",
>     "sec-fetch-mode": "cors",
>     "sec-fetch-site": "same-origin",
>     "sec-gpc": "1"
>   },
>   "referrer": "http://localhost:8000/register",
>   "referrerPolicy": "strict-origin-when-cross-origin",
>   "body": "{\"username\":\"test1\",\"email\":\"test1@test.com\",\"first_name\":\"test\",\"last_name\":\"tester\",\"password\":\"password\",\"roles\":[\"Test Role\"]}",
>   "method": "POST",
>   "mode": "cors",
>   "credentials": "include"
> });
> ```

I'm not sure what the intended purpose of roles is yet. It was just something included in the mock-up. I initialized it as an empty array so that we could potentially add dummy strings to it for mocking.

2021-03-14 22:26 UTC, powell759 commented
We're exposing private information to anyone who knows an email address through the "Get Account By Email" API. Is there a reason that this is public facing?

2021-03-14 22:30 UTC, ecaoile commented
> 
> 
> We're exposing private information to anyone who knows an email address through the "Get Account By Email" API. Is there a reason that this is public facing?

I'll double check, but I think it's not being used anymore. E-mail check is being done in the other endpoints now. If that's the case, I'll delete it.

2021-03-14 22:37 UTC, ecaoile commented
Password format checks have been added to post and patch. Get account by e-mail endpoint deleted.

2021-03-14 22:43 UTC, powell759 commented
> > We're exposing private information to anyone who knows an email address through the "Get Account By Email" API. Is there a reason that this is public facing?
> 
> I'll double check, but I think it's not being used anymore. E-mail check is being done in the other endpoints now. If that's the case, I'll delete it.

Sounds good - it was also exposing UUID allowing me to delete / update other accounts

2021-03-15 00:53 UTC, jtuckerk requested changes
I've finally gone through this line by line! you did so much!

sorry for the delay on this, I was trying to finish up yesterday but didnt quite get the deployed version working. Its up now at https://staging-volunteer-portal-dv734ug3ua-uc.a.run.app/ there is  an issue with the routes so the google login isnt working, ~I think it has to do with the change from 8080 in the config to 8000, but I'm verifying that now. The manual account creation works for now tho.~ @trippersham I think you had asked if the staging url is constant, It is, and I guess we need to include it somewhere in the config for this to send the token back to the backend

Theres some overlap in mine and maxes comments but I've just left them. I think we dont need to make all the changes to the api just yet to finish up fully securing all of the calls. We can gets trips input since he set up the auth and this will just become too big of a PR.

I just have a few things I want the UX peeps to look at which is why ive put it up on that link above, and a handfull of minor change requests

2021-03-15 00:53 UTC, jtuckerk commented on client/src/components/OldRegister.js
> +import React from 'react';
Should we just delete this file?

2021-03-15 00:53 UTC, jtuckerk commented on api/api.py
> +@app.get("/api/accounts/{uuid}", response_model=AccountResponseSchema)
could we put al the account routes into their own account_api.py file? like the auth.py with auth.router

2021-03-15 00:53 UTC, jtuckerk commented on api/auth.py
> +def create_access_and_refresh_tokens(user_id: str, Authorize: AuthJWT):
This is the second instance  of this function, can we just import it from here into api.py?

2021-03-15 00:53 UTC, jtuckerk commented on api/api.py
> +    Authorize.jwt_required()
This just ensures that they have a valid jwt, but doesnt actually prevent people from getting other peoples' account info.

2021-03-15 00:53 UTC, jtuckerk commented on api/api.py
> +    return db.query(Account).filter_by(email=email).first()
Auth! fine to leave all the auth stuff for a later PR, but can we add TODOs so we dont forget/people know its intentionally left out for now?

2021-03-15 00:53 UTC, jtuckerk commented on api/auth.py
> +@router.post("/auth/basic")
this wil be the route /auth/auth/basic -- there is an auth/auth/google above so maybe that's the way it's supposed to be?

2021-03-15 00:53 UTC, jtuckerk commented on api/bootstrap.py
> +    db_url = Connections[key]['url'].replace(
this replace call can just be removed. it was forcing all dbs to postrgress, but I dont think it really even makes sense any more given the shape of the configs

2021-03-15 00:53 UTC, jtuckerk commented on api/config.yaml
> +    host:
I dont think we need these? and if we do something else is wonky.

2021-03-15 00:53 UTC, jtuckerk commented on api/schemas/account.py
> +    old_password: Text
does this need to be "old"?

2021-03-15 00:53 UTC, jtuckerk commented on api/schemas/account.py
> +class PartialAccountSchema(BaseModel):
was above class going to be used for the /api/accounts/{uuid} updated_password route? seems like for now that class having uuid and password should be sufficient.

2021-03-15 00:53 UTC, jtuckerk commented on api/api.py
> +@app.patch("/api/accounts/{uuid}", response_model=AccountResponseSchema)
Is patch typically used for just password changes? would someone well versed in rest/http things know from this url and the patch that this only updates the password for an account?

2021-03-15 00:53 UTC, jtuckerk commented on api/models/account_settings.py
> +    initiative_map = Column('initiative_map', JSON, default={}, nullable=False)
could you add a comment indicating what the keys and values of this map are? initiative_name -> isSubscribed?

I think we'll want to talk with @trippersham about how hes setting up the subscriptions since I think he's got a different plan in mind. From what I understand the subscriptions will be their own DB where it's an account foreign key is included and each row represents a subscription so that the same structure can be used for accounts and non-account based subscriptions

2021-03-15 00:53 UTC, jtuckerk commented on api/security.py
> +    return pwd_context.encrypt(password)
Getting a deprecation warning for this in the tests:

/api/security.py:11: DeprecationWarning: the method passlib.context.CryptContext.encrypt() is deprecated as of Passlib 1.7, and will be removed in Passlib 2.0, use CryptContext.hash() instead.
    return pwd_context.encrypt(password)

2021-03-15 00:53 UTC, jtuckerk commented on client/package.json
> +  "version": "1.0.0",
nice

2021-03-15 00:53 UTC, jtuckerk commented on client/package-lock.json
> +      "version": "5.0.1",
I'm seeing a few packages that look downgraded, think that's on purpose or a merge thing?

2021-03-15 00:53 UTC, jtuckerk commented on api/models/account.py
> +    state = Column('state', String(32), nullable=True)
Can we  start off including zipcode as well (or instead?) we've had some volunteers do a bunch of work to get zip code to federal and state congressional districts mappings and its also pretty easy to map zip to city and state if we want

2021-03-15 00:53 UTC, jtuckerk commented on client/src/components/Account/AccountNav.js
> +      <Nav
I've spun up a staging version of this PR [here](https://staging-volunteer-portal-dv734ug3ua-uc.a.run.app/) so that the UX folks can take a look. I'd like to get their input on his nav setup and a couple of other things.

2021-03-15 00:53 UTC, jtuckerk commented on client/src/components/Header/LoggedInMenu.js
> +          (user.username === 'andyfromtheblock' ? andyPic : placeholderImg)
This probably doesnt matter, but did you intend to leave this in? we could hard code these values into the DB config?

2021-03-15 00:56 UTC, jtuckerk commented on api/config.yaml
> +    host:
checked in branch release-staging-ux-review, this change breaks the configs. that branch has a working config.

2021-03-15 01:05 UTC, ecaoile commented on api/api.py
> +    return db.query(Account).filter_by(email=email).first()
I got rid of it.

2021-03-15 01:09 UTC, ecaoile commented on client/src/components/Header/LoggedInMenu.js
> +          (user.username === 'andyfromtheblock' ? andyPic : placeholderImg)
Oh, that was just a funny easter egg since I wanted to test accounts with multiple pictures. I don't think many people are gonna want to go by andyfromtheblock. Are we going to integrate picture upload in the future?

2021-03-15 01:16 UTC, powell759 commented on api/api.py
> +    Authorize.jwt_required()
+1 and in general let's keep UUID (and database keys in general) off the client side / out of responses. Can we associate tokens with accounts on the backend and use them (rather than UUID) for state-changing operations?

2021-03-15 01:24 UTC, ecaoile commented on api/api.py
> +@app.get("/api/accounts/{uuid}", response_model=AccountResponseSchema)
I was scared it was going to break if I tried to make it modular, but yes, we should do that. Api.py is getting too fat.

2021-03-15 01:24 UTC, ecaoile commented on client/package-lock.json
> +      "version": "5.0.1",
Merge blues.

2021-03-15 01:26 UTC, ecaoile commented on client/src/components/OldRegister.js
> +import React from 'react';
I don't know if we were gonna use any of this later. Figure we might at least have use for that social share.

2021-03-15 02:05 UTC, ecaoile commented on api/api.py
> +    Authorize.jwt_required()
I don't know if that's legal, but I'll see what I can do.

2021-03-15 02:58 UTC, jtuckerk commented on client/src/components/Header/LoggedInMenu.js
> +          (user.username === 'andyfromtheblock' ? andyPic : placeholderImg)
Im fine with easter eggs
yeah I think we should, makes it feel more like a community

2021-03-15 03:02 UTC, jtuckerk commented
re: the bit about auth not working in staging. that's more complicated and we can deal with that outside of this PR. 

I think we'll want to include `proxy_set_header Host $host;` for the api in the nginx conf since I'm seeing that the auth redirect is trying to hit the docker internal http:/api:8081 domain, but just adding that messes up other things so theres more digging that needs to be done. I think @trippersham  has already grappled with this problem a bit

2021-03-15 04:59 UTC, ecaoile commented on api/api.py
> +@app.get("/api/accounts/{uuid}", response_model=AccountResponseSchema)
Ok, figured it out

2021-03-15 05:06 UTC, ecaoile commented on api/api.py
> +    Authorize.jwt_required()
Looks like it might be legal as long as the uuid is stored in the token somewhere. Don't think we can completely hide it from the front end, but we can make it less visible.

2021-03-15 16:04 UTC, powell759 commented on api/api.py
> +    Authorize.jwt_required()
@jtuckerk's point is that while we are validating the session JWT we aren't validating that it is that user's data they are accessing. This means that any user with a valid JWT can preform CRUD operations on any user's account. What we need to prevent that is to have an association between session and account, and we need to validate that on requests (At some point we may want privileged accounts but we can cross that bridge when we come to it).

My point was that UUID shouldn't be on the client side or used in the path for APIs at all. Exposing database keys increases blast radius of any potential attack. In Tucker's example a user can update another person's information - if UUID wasn't an argument that wouldn't be possible.

We don't need to worry about storing UUID in the token and I wouldn't recommend that anyway, I believe that this JWT is only signed - not encrypted - and the info could be extracted. Take a look at the "Get All Settings" API `/api/account_settings/` - this takes no argument yet returns the user's account. That tells me we already are making an association on the backend between the JWT session and a user.

All access/updates should function like this endpoint so we have:
- a JWT required to access
-  resource accessed defined by session rather than UUID

2021-03-15 16:19 UTC, ecaoile commented on api/api.py
> +    Authorize.jwt_required()
I get what Tucker was saying, but I'm just unsure how to get the proper user credentials if we don't pass some kind of primary key even if it isn't the UUID. It's simple enough to get the jwt subject and ensure that it's equivalent to the current user, but if we don't use UUID, what do we use? We need a unique identifier, so it would have to be e-mail or username. In that case, wouldn't that key serve the same purpose as UUID even if we don't pass it into the API endpoint address? 

The get all for account_settings actually returns settings from all users. This needs to be disabled too until we configure admin privileges.

2021-03-15 17:07 UTC, jtuckerk commented on api/auth.py
> +            city=user['location'].split(', ')[0],
I dont have my location set for github so this fails:
```
api_1     |     return await dependant.call(**values)
api_1     |   File "./auth.py", line 182, in authorize_github
api_1     |     city=user['location'].split(', ')[0],
api_1     | AttributeError: 'NoneType' object has no attribute 'split'
```

2021-03-16 00:07 UTC, ecaoile commented on api/auth.py
> +            city=user['location'].split(', ')[0],
Oof, I see GitHub makes a lot of the fields optional. Probably best to always do a null check for string splits anyway. Silly me.

2021-03-16 03:27 UTC, ecaoile commented on api/models/account.py
> +    state = Column('state', String(32), nullable=True)
added zip code to front end and back end

2021-03-16 03:48 UTC, powell759 commented on api/api.py
> +    Authorize.jwt_required()
Okay - took a closer look this evening - I'm familiar with session / cookie based authentication where you'd provide a user with an expiring session and associate that to the user on the backend. That way you'd never have the need for a user id on the client.

Did some learning and it looks like the JWT / token-based authentication is a whole different approach with one of the main benefits being not needing that datastore for sessions. So implementing a lookup kinda gets rid of that benefit. So if we are going with a token-based authentication then you are right, we'll need to include some type of unique key, and whether or not that is UUID doesn't really matter (it looks UUID is already the subject claim so might as well leave it).

I think there are some minor drawbacks to using JWT like not being able to revoke authorizations - but I'm not sure we'll really have a use case for that.

So nvm the UUID comment - let's just add the subject check and disable the all accounts API.

2021-03-16 04:36 UTC, ecaoile commented on api/api.py
> +    Authorize.jwt_required()
Added token check on all the account endpoints except the posts. I feel like there should be some kind of check for post too, but I don't know what the best practice is when we haven't created a user yet. I wonder if the app should issue some kind of non-account jwt so that it knows the request was being made from the app.

2021-03-16 04:51 UTC, ecaoile commented on api/auth.py
> +@router.post("/auth/basic")
It's using api as a prefix, not auth.You can see on the front end that it's calling /api/auth/basic

2021-03-16 04:59 UTC, ecaoile commented on api/schemas/account.py
> +class PartialAccountSchema(BaseModel):
I think originally I was planning to use this class for patch in general (i.e. making a change to one prop), but something about it was wonky. I forgot off the top of my head. Maybe it had something to do with not knowing how to get the props that were changed...or maybe it was the password. If you know how to properly do a patch with SQL Alchemy, maybe you could help me out here.

2021-03-16 05:00 UTC, ecaoile commented on api/schemas/account.py
> +    old_password: Text
I guess we could call it current_password, but we're trying to get rid of it. Is old_password misleading?

2021-03-16 05:06 UTC, ecaoile commented on api/auth.py
> +def create_access_and_refresh_tokens(user_id: str, Authorize: AuthJWT):
deleted and importing from account_api

2021-03-16 05:11 UTC, ecaoile commented on api/config.yaml
> +    host:
Grabbed the config from that branch.

2021-03-16 05:12 UTC, ecaoile commented on api/security.py
> +    return pwd_context.encrypt(password)
changed to .hash()

2021-03-16 05:17 UTC, ecaoile commented on api/bootstrap.py
> +    db_url = Connections[key]['url'].replace(
So just leave it as `db_url = Connections[key]['url']`?

2021-03-16 05:24 UTC, ecaoile commented on api/models/account_settings.py
> +    initiative_map = Column('initiative_map', JSON, default={}, nullable=False)
Yes. A lot of this data structure is guessing since I don't know for sure what we're doing with some of these props. I think I know what you mean with that subscription and account table, though We use a few of those at my workplace. I guess for that table, we could use e-mails so that it works for account and non-account subs.

2021-03-16 17:34 UTC, jtuckerk commented on api/auth.py
> +            city=None if user['location'] is None else user['location'].split(', ')[
could do `user.get('location', None)` instead of `user['location']` just in case the field does not exist. but if the api is currently sending none, I'd be surprised if they started dropping the field entirely, so its probably fine as is.

2021-03-16 18:39 UTC, jtuckerk commented on client/package-lock.json
> +      "version": "5.0.1",
oh :( is there a simple way to update everything to the latest version?

2021-03-17 00:59 UTC, ecaoile commented on client/package-lock.json
> +      "version": "5.0.1",
I'm not sure if it's really an issue. It's possible I accidentally downgraded one of the packages in packages.json after merging previously, but we typically don't tamper with the package-lock file much. That just tends to get generated after adding the dependencies and then running npm install.

2021-03-17 04:30 UTC, ecaoile commented on client/src/components/OldRegister.js
> +import React from 'react';
Nevermind, I see we're getting rid of that donation link thing. I'll just delete this then.

2021-03-18 19:23 UTC, jtuckerk commented on client/package-lock.json
> +      "version": "5.0.1",
ok that's good enough for me!

2021-03-18 19:24 UTC, jtuckerk commented on client/src/components/Account/AccountNav.js
> +      <Nav
Their comments can be addressed in later PRs, resolving

2021-03-19 05:25 UTC, ecaoile commented on api/api.py
> +    Authorize.jwt_required()
Going to resolve this too. Post endpoints are still kinda sus, but we can improve on them later.

2021-03-21 21:45 UTC, jtuckerk approved these changes
Good to go! 
there are just a few things we'll probably want to do in followup CLs, I've aggregated them here:

- We'll need to force the email duplicate checker to compare in a case insensitive manner. right now I can create Tucker@gmail and tucker@gmail.
- also We should remove periods from before the @ sign before checking. [dots don't matter in gmail](https://support.google.com/mail/answer/7436150?hl=en). I assume some other email providers do the same.
- Right now for the login and create buttons, the oauth login flows both create an account if one does not exist. I imagine that would confuse people if they have an account but forget how they signed up. if they try logging in with gmail it will appear we've wiped out their settings.
- fakegithubemail - can this look different?
- account API auth finishing touches/tests
- separate various account routes with additional path names for a more hierarchical structure.
- route for the logout delete route -- just a lint thing

2021-03-21 21:45 UTC, jtuckerk commented on api/auth.py
> +    email_to_use = user['email'] or user['login'] + '@fakegithubemail.com'
Could we include the username in a message: "Github auth account: {username}" or something similar to avoid confusion?

2021-03-21 21:45 UTC, jtuckerk commented on api/account_api.py
> +def create_settings(settings: AccountSettingsSchema, Authorize: AuthJWT = Depends(), db: Session = Depends(get_db)):
Any way we can make this dependent on account creation? could we create the settings in the create account call and have an authed request later to get the settings or we do an authed request to this method after account creation

2021-03-21 21:45 UTC, jtuckerk commented on api/auth.py
> +@router.post("/auth/basic")
yeah I was confused. I thought the api prefix was we had was /api/auth for some reason

2021-03-21 21:45 UTC, jtuckerk commented on api/auth.py
> +@router.post("/auth/basic")
Wondering if we should organize them that way. might make the auto generated docs a little cleaner. can be a later PR.

2021-03-21 21:45 UTC, jtuckerk commented on api/auth.py
> +@ router.delete("/logout")
delete space? @ router (surprisingly doesnt seem to matter)

2021-03-21 21:47 UTC, jtuckerk commented
My review was very light on the react stuff, but I think we can merge without a react review unless @powell759, @vai0, or you feel differently

2021-03-21 22:17 UTC, ecaoile commented on api/auth.py
> +    email_to_use = user['email'] or user['login'] + '@fakegithubemail.com'
![image](https://user-images.githubusercontent.com/34725510/111922718-8bac1d80-8a58-11eb-8cd6-541c07a11b3e.png)

Disabled username change for GitHub users and wrote a note for fake e-mails.

2021-03-21 22:19 UTC, ecaoile commented on api/auth.py
> +@ router.delete("/logout")
space deleted

2021-03-21 23:31 UTC, ecaoile commented
> 
> 
> Good to go!
> there are just a few things we'll probably want to do in followup CLs, I've aggregated them here:
> 
>     * We'll need to force the email duplicate checker to compare in a case insensitive manner. right now I can create Tucker@gmail and tucker@gmail.
> 
>     * also We should remove periods from before the @ sign before checking. [dots don't matter in gmail](https://support.google.com/mail/answer/7436150?hl=en). I assume some other email providers do the same.
> 
>     * Right now for the login and create buttons, the oauth login flows both create an account if one does not exist. I imagine that would confuse people if they have an account but forget how they signed up. if they try logging in with gmail it will appear we've wiped out their settings.
> 
>     * fakegithubemail - can this look different?
> 
>     * account API auth finishing touches/tests
> 
>     * separate various account routes with additional path names for a more hierarchical structure.
> 
>     * route for the logout delete route -- just a lint thing

I've added form sanitization with space trim for some fields and lowercase + period removal for e-mails. Also hiding e-mails with message for GitHub users. I'll leave this PR up for a few hours in case anyone else wants to review, and then I'll merge it later in the evening.

2021-03-22 04:07 UTC, ecaoile commented on api/account_api.py
> +def create_settings(settings: AccountSettingsSchema, Authorize: AuthJWT = Depends(), db: Session = Depends(get_db)):
Probably, but that will require adding some default dummy values into a class like I did on the JS side. If I could do that, I wouldn't have to change any other code besides adding the require JWT and making the call from the account post to the settings. I'll address this in the next PR.

2021-03-22 04:08 UTC, merged